version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: dhaka-tesla-db-dev
    restart: always
    environment:
      POSTGRES_USER: tesla_admin
      POSTGRES_PASSWORD: tesla_secret_password
      POSTGRES_DB: dhaka_tesla_pool
    ports:
      - "5432:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
volumes:
  pgdata_dev:
